---
- name: SysAdmins - Create user
  user:
    name: "{{ item.key }}"
    groups: "{{ default_group }}"
    append: yes
    state: "{{ item.value.state }}"
    shell: /bin/bash
  with_dict: "{{ sysadmins }}"

- name: SysAdmins - copy ssh keys
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ lookup('file', item.value.key) }}"
    state: "{{ item.value.state }}"
  when: item.value.state == "present"
  with_dict: "{{ sysadmins }}"

- name: SysAdmins - add custom sudoer file
  template:
    src: sysadmin.sudoer.j2
    dest: "/etc/sudoers.d/90-{{ item.key }}"
    mode: 0440
  when: item.value.state == "present"
  with_dict: "{{ sysadmins }}"
