---
- name: Install virtualenv
  apt:
    pkg=virtualenv
    state=present
  become: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version != '14.04'

- name: Check if virtualenv is already created
  stat:
    path: "{{ ansible_env.HOME }}/odoo-venv"
  register: env

- name: Manually create the initial virtualenv
  command: virtualenv "{{ ansible_env.HOME }}/odoo-venv" creates="{{ ansible_env.HOME }}/.odoo-env"
  when: env.stat.isdir is undefined
