
# from galaxy
- src: geerlingguy.postgresql
  version: 1.3.1

- src: carlosbuenosvinos.ansistrano-deploy
  version: 2.7.0

- src: geerlingguy.security
  version: 1.5.0

- src: jdauphant.nginx
  version: v2.11.1

- src: geerlingguy.certbot
  version: 2.0.0
