---
# Add your ssh public key in pub_keys folder and add it to this list
# exemple:                        | Your name
#   file: ../pub_keys/example.pub | Key file path
#   state: present                | present to add or absent (absent to remove authorized key)

users:
  odoo:
    key: "{{ lookup('env', 'HOME' ) }}/.ssh/id_rsa.pub" # Needed to provision and deploy
    state: present
    group:
  dani:
    key: ../pub_keys/dani.pub
    state: present
    group: odoo

custom_modules_repo: https://github.com/danypr92/odoo-organization-custom-modules.git
custom_modules_repo_branch: master
log_path: /var/log/odoo
