---
# Add your ssh public key in pub_keys folder and add it to this list
# users:                                | sysadmins or users
#    example:                           | Your name
#     key: ../pub_keys/ssh_pub_key.pub  | Key file path
#     state: present                    | present (add or maintain) or absent (remove)

sysadmins:
  dani:
    key: ../pub_keys/dani.pub
    state: present

users:
  dani2:
    key: ../pub_keys/dani.pub
    state: present
  dani3:
    key: ../pub_keys/dani.pub
    state: present

custom_modules_repo: https://github.com/danypr92/odoo-organization-custom-modules.git
custom_modules_repo_branch: master
log_path: /var/log/odoo
