--- # Setup a default user - needs to be run as root.
- name: create deploy user
  user:
    name="{{ user }}"
    groups=adm,dialout,cdrom,floppy,audio,dip,video,plugdev,netdev,sudo
    append=yes
    state=present
    shell=/bin/bash

- name: ssh keys
  authorized_key:
    user={{ user }}
    key="{{ lookup('file', item.value.key) }}"
    state={{ item.value.state }}
  with_dict: "{{ ssh_keys }}"


- name: add custom sudoer file
  template:
    src=sudoer.j2
    dest="/etc/sudoers.d/90-{{ user }}"
    mode=0440
