---
# Setup a default user - Work user.

- name: create default_user
  user:
    name=odoo
    append=yes
    state=present
    shell=/bin/bash

- name: add default_user  sudoer file
  become: yes
  template:
    src=odoo.sudoer.j2
    dest=/etc/sudoers.d/1-odoo
    mode=0440


