---

- name: Copy systemd service
  template:
    src="odoo.service.j2"
    dest="/etc/systemd/system/odoo.service"
    mode="0744"
    owner="{{ user }}"
    group="{{ user }}"
  become: yes

- name: Enable service
  become: yes
  systemd:
    name: odoo.service
    enabled: yes
    state: started
    daemon_reload: yes
