---
# Add your ssh public key in pub_keys folder and add it to this list
# users:                                | sysadmins or users
#    example:                           | Your name
#     key: ../pub_keys/ssh_pub_key.pub  | Key file path
#     state: present                    | present (add or maintain) or absent (remove)

# In development environment you can access to the server with `default_user`
development_user: "{{ lookup('env', 'USER') }}"

sys_admins:
  - name: odoo
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present
  - name: "{{ development_user }}"
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present

developers: []

remove_default_user_ssh_keys: false

custom_modules_repo: https://github.com/danypr92/odoo-organization-custom-modules.git
custom_modules_repo_branch: master

log_path: /var/log/odoo
# Log levels: critical, error, warn, debug
log_level: debug

developer_email:

# Declare 'development_environment' var with "true" value to skip SSL and nginx tasks.
development_environment: true
