---
- name: Copy systemd service
  template:
    src="odoo.service.j2"
    dest="/etc/systemd/system/odoo.service"
    mode=2775
    owner=odoo
    group=odoo
  become: yes

- name: Enable service
  become: yes
  systemd:
    name: odoo.service
    enabled: yes
    state: started
    daemon_reload: yes
