---
- name: Copy systemd service
  template:
    src: "odoo.service.j2"
    dest: "/etc/systemd/system/odoo.service"
    mode: 02775
    owner: "{{ default_user }}"
    group: "{{ default_group }}"

- name: Enable service
  systemd:
    name: odoo.service
    enabled: yes
    state: started
    daemon_reload: yes
