---
- name: Create Odoo directory
  become: yes
  file:
    path="{{ odoo_path }}"
    state=directory
    group=odoo
    mode=2775

- name: Create share directory
  become: yes
  file:
    path="{{ odoo_path }}/shared"
    state=directory
    group=odoo
    mode=2775

- name: Create custom modules directory
  become: yes
  file:
    path="{{ custom_modules_path }}"
    state=directory
    mode=2775
    group=odoo

- name: Create log dir "{{ log_path }}"
  become: yes
  file:
    path="{{ log_path }}"
    state=directory
    group=odoo
    mode=2777

- name: Create log file "{{ log_path }}"
  become: yes
  file:
    path="{{ log_path }}/odoo.log"
    group=odoo
    state=touch
    mode=2777

- name: Create virtualenv directory
  become: yes
  file:
    path="{{ venv_path }}"
    state=directory
    mode=2775
    group=odoo
