---
- name: Create Odoo directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 02775
  with_items:
    - "{{ odoo_path }}"
    - "{{ odoo_path }}/shared"
    - "{{ custom_modules_path }}/current"

- name: Create log dir "{{ log_path }}"
  file:
    path: "{{ log_path }}"
    state: directory
    group: "{{ default_group }}"
    mode: 02777

- name: Create log file "{{ log_path }}"
  file:
    path: "{{ log_path }}/odoo.log"
    group: "{{ default_group }}"
    state: touch
    mode: 02777

- name: Download Odoo
  get_url:
    url: "{{ odoo_url }}"
    dest: "{{ odoo_download_path }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    
- name: Uncompress downloaded Odoo
  unarchive:
    src: "{{ odoo_download_path }}"
    dest: "{{ odoo_path }}"
    remote_src: yes
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    extra_opts: [--strip-components=1]

- name: Install Odoo python requirements
  pip:
    requirements: "{{ odoo_path }}/requirements.txt"
    virtualenv: "{{ venv_path }}"

- name: Build Odoo exec
  shell: "cd {{ odoo_path }} && {{ venv_path }}/bin/python setup.py build"
  
- name: Install Odoo dependencies
  shell: "cd {{ odoo_path }} && {{ venv_path }}/bin/python setup.py install"

- name: Add Odoo config
  template:
    src: odoo.conf.j2
    dest: "{{ odoo_path }}/shared/odoo.conf"
    mode: 0774
    group: "{{ default_group }}"

- name: Restart Odoo service
  service:
    name: odoo
    state: restarted
