---
- name: Create Odoo directory
  file:
    path: "{{ odoo_path }}"
    state: directory
    group: "{{ default_group }}"
    mode: 02775

- name: Create share directory
  file:
    path: "{{ odoo_path }}/shared"
    state: directory
    group: "{{ default_group }}"
    mode: 02775

- name: Create custom modules directory
  file:
    path: "{{ custom_modules_path }}/current"
    state: directory
    mode: 02775
    group: "{{ default_group }}"

- name: Create log dir "{{ log_path }}"
  file:
    path: "{{ log_path }}"
    state: directory
    group: "{{ default_group }}"
    mode: 02777

- name: Create log file "{{ log_path }}"
  file:
    path: "{{ log_path }}/odoo.log"
    group: "{{ default_group }}"
    state: touch
    mode: 02777

- name: Download and extract Odoo
  unarchive:
    src: "{{ odoo_url }}"
    dest: "{{ odoo_path }}"
    force: yes
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Install Odoo python requirements
  pip:
    requirements: "{{ odoo_path }}/requirements.txt"
    virtualenv: "{{ venv_path }}"

- name: Build Odoo exec
  shell: "cd {{ odoo_path }} && {{ venv_path }}/bin/python setup.py build"

- name: Install Odoo dependencies
  shell: "cd {{ odoo_path }} && {{ venv_path }}/bin/python setup.py install"

- name: Add Odoo config
  template:
    src: odoo.conf.j2
    dest: "{{ odoo_path }}/shared/odoo.conf"
    mode: 0774
    group: "{{ default_group }}"

- name: Restart service (command)
  command: "sudo systemctl restart odoo.service"
