---
- name: Create `odoo` user
  user:
    name: odoo
    groups: "{{ default_group }}"
    group: "{{ default_group }}"
    append: yes
    state: present
    shell: /bin/bash

- name: Create sudoers for `odoo` user
  template:
    dest: /etc/sudoers.d/odoo
    mode: 0440
    owner: root
    group: root
    src: sudoers.odoo
    validate: "/usr/sbin/visudo -cf %s"

- name: Add system administrator SSH public keys to `odoo` user
  authorized_key:
    user: odoo
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ sys_admins }}"

- name: Add developers SSH public keys to `odoo` user
  authorized_key:
    user: odoo
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ developers }}"
