---

# Setup a default user - Work user.

- name: create users
  become: yes
  user:
    name="{{ item.key }}"
    groups="{{ item.value.group }}"
    append=yes
    state="{{ item.value.state }}"
    shell=/bin/bash
  with_dict: "{{ users }}"

- name: ssh keys
  become: yes
  authorized_key:
    user={{ item.key }}
    key="{{ lookup('file', item.value.key) }}"
    state={{ item.value.state }}
  when: item.value.state == "present"
  with_dict: "{{ users }}"

- name: add custom sudoer file
  become: yes
  template:
    src=sudoer.j2
    dest="/etc/sudoers.d/90-{{ item.key }}"
    mode=0440
  when: item.value.state == "present"
  with_dict: "{{ users }}"
