---
- name: Create virtualenv directory
  file:
    path: "{{ venv_path }}"
    state: directory
    mode: 02775
    group: "{{ default_group }}"

- name: Check if virtualenv is already created
  stat:
    path: "{{ venv_path }}/bin"
  register: env

- name: Manually create the initial virtualenv
  command: "virtualenv {{ venv_path }}"
  when: env.stat.isdir is undefined

- name: Change virtualenv permissions
  file:
    path: "{{ venv_path }}"
    owner: odoo
    group: "{{ default_group }}"
    mode: 02775
    recurse: yes
