---
- name: Check if virtualenv is already created
  stat:
    path: "{{ venv_path }}/bin"
  register: env

- name: Manually create the initial virtualenv
  command: "virtualenv {{ venv_path }}"
  when: env.stat.isdir is undefined
