---
- name: provision
  hosts: odoo_servers
  become: yes
  roles:
    - role: geerlingguy.security

    - role: geerlingguy.postgresql
      vars:
        postgresql_users:
          - name: "{{ odoo_user }}"
            role_attr_flags: CREATEDB
        postgresql_databases:
          - name: "{{ database_name }}"

    - role: coopdevs.certbot_nginx
      vars:
          domain_name: "{{ inventory_hostname }}"
          letsencrypt_email: "{{ developer_email }}"
      when: not development_environment

    - role: jdauphant.nginx
      when: not development_environment
