---
- name: provision
  hosts: odoo_servers
  remote_user: "{{ user }}"

  roles:
    - role: common
      tags: common

    # Need install postgresql, then create a postgres user named like your login
    - role: geerlingguy.postgresql
      become: yes
      tags: postgresql

    # Install npm and less CSS
    - role: nodejs
      tags: nodejs

