---
- name: provision
  hosts: odoo_servers
  become: yes
  roles:
    - role: geerlingguy.security

    - role: geerlingguy.postgresql

    - role: postgresql-odoo

    - role: coopdevs.certbot_nginx
      vars:
          domain_name: "{{ inventory_hostname }}"
          letsencrypt_email: "{{ certificate_authority_email }}"
      when: not development_environment

    - role: jdauphant.nginx
      when: not development_environment

    - role: coopdevs.odoo-role
      vars:
        odoo_db_admin_password: "{{ odoo_admin_password }}"
        odoo_core_modules: "{{ odoo_install_core_modules }}"
        odoo_db_name: "{{ database_name }}"
        odoo_code_from: "{{ code_from }}"
      tags: odoo
