---
- name: provision
  hosts: odoo_servers
  remote_user: "{{ user }}"

  vars:
    example: example

  roles:
    - role: common
      tags: common

    # Need install postgresql, then create a postgres user named like your login
    - role: geerlingguy.postgresql
      become: yes
      tags: postgresql

    # Install npm and less CSS
    - role: nodejs
      tags: nodejs

    # # Python dependencies listed in the requirements.txt file
    - role: pythonenv
      tags: pythonenv
