---

# User name and password for running ansible on host
user: odoo

# venv path
venv_path: /opt/.odoo_venv

# Deploy path
odoo_path: /opt/odoo
custom_modules_path: /opt/custom_modules

# Use correct python2.7 interpeter
ansible_python_interpreter: "/usr/bin/python2.7"

postgresql_users:
  - name: "{{ user }}"
    role_attr_flags: CREATEDB
