---

default_user: odoo
default_group: odoo
remove_default_user_ssh_keys: true

# venv path
venv_path: /opt/.odoo_venv

# Odoo
odoo_version: 10.0
odoo_release: 20170914
odoo_path: /opt/odoo
odoo_url: "https://nightly.odoo.com/{{ odoo_version }}/nightly/src/odoo_{{ odoo_version }}.{{ odoo_release }}.tar.gz"
odoo_download_path: /tmp/odoo_{{ odoo_version }}.{{ odoo_release }}.tar.gz
odoo_bin_path: "{{ odoo_path }}/build/scripts-2.7/odoo"
odoo_python_path: "{{ venv_path }}/bin/python"
odoo_config_path:  /etc/odoo
custom_modules_path: /opt/custom_modules

# Use correct python2.7 interpeter
ansible_python_interpreter: "/usr/bin/python2.7"

postgresql_users:
  - name: "{{ default_user }}"
    role_attr_flags: CREATEDB

# Nginx configuration
nginx_configs:
  upstream:
    - upstream odoo { server 127.0.0.1:8069; }

nginx_sites:
  odoo:
    - |
      listen 80;
      server_name {{ inventory_hostname }};
      rewrite ^(.*)$ https://$host$1 permanent;
  odoo.ssl:
    - |
      listen 443 ssl;
      ssl_certificate /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
      server_name {{ inventory_hostname }};
      proxy_read_timeout 720s;
      proxy_connect_timeout 720s;
      proxy_send_timeout 720s;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      ssl on;
      access_log /var/log/nginx/odoo.access.log;
      error_log /var/log/nginx/odoo.error.log;
      location / {
        proxy_redirect off;
        proxy_pass http://odoo;
      }
      gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
      gzip on;
